# -*- coding: utf-8 -*-
"""실습)퍼셉트론으로 논리연산

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPLZUdehp_VdP7-AliQYhV2JsNTbH559

한글을 표현하기 위한 라이브러리 설치
"""

!pip install koreanize_matplotlib
import koreanize_matplotlib

"""#1. 진리표에 대한 이해
-AND연산, OR연산, XOR연산
"""

import numpy as np
import matplotlib.pyplot as plt

# AND 연산입력값과 분류 결과 설정
inputs = [(1, 1), (0, 1), (1, 0), (0, 0)] #AND 연산으로 연습해보자.
results = [1, 0, 0, 0]

plt.scatter([point[0] for point in inputs], [point[1] for point in inputs], c=results, cmap='bwr')
plt.show()

x1=1
x2=1

y=2*x1+2*x2-3
if y>=0:
    print(1)
else:
    print(0)

import matplotlib.pyplot as plt

# AND 연산입력값과 분류 결과 설정
x1=[1,0,1,0]
x2=[1,1,0,0]
y=[1,0,0,0]

plt.scatter(x1,x2, c=y, cmap='bwr')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# AND 연산입력값과 분류 결과 설정
x1=[1,0,1,0]
x2=[1,1,0,0]
r=[1,0,0,0]

# 가중치와 편향 설정
w= [2, 2]
b= -3

# 그래프 생성을 위한 데이터 포인트 생성
x = np.linspace(-0.5, 1.5, 100)
y = -w[0]/w[1]*x-b/w[1]

#선으로 구분하는 그래프그리기
plt.plot(x,y)
plt.scatter(x1,x2, c=r, cmap='bwr')
plt.xlabel('x1')
plt.ylabel('x2')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# AND 연산입력값과 분류 결과 설정
x1=[1,0,1,0]
x2=[1,1,0,0]
r=[1,0,0,0]

#활성화함수
def step_function(x):
    return np.where(x >= 0, 1, 0)

# 가중치와 편향 설정
w= [2, 2]
b= -3

# 그래프 생성을 위한 데이터 포인트 생성
x = np.linspace(-0.5, 1.5, 100)
y = np.linspace(-0.5, 1.5, 100)
X, Y = np.meshgrid(x, y)
z = b +w[0] * X + w[1] * Y
Z=step_function(z)

# 그래프 그리기
plt.contourf(X, Y, Z, levels=[-np.inf, 0, np.inf], colors=('blue', 'red'), alpha=0.2)
plt.scatter(x1,x2, c=r, cmap='bwr')
plt.xlabel('x1')
plt.ylabel('x2')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# XOR 입력값과 출력값
inputs = [(1, 1), (0, 1), (1, 0), (0, 0)]
results = [0, 1, 1, 0]

# 가중치와 편향
w1 = [-2, -2]
w2 = [2, 2]
w3 = [1, 1]
b1 = 3
b2 = -1
b3 = -2

def step_function(x):
    return np.where(x >= 0, 1, 0)

# 결과 저장용
outputs = []

for x1, x2 in inputs:
    z1 = w1[0]*x1 + w1[1]*x2 + b1
    z2 = w2[0]*x1 + w2[1]*x2 + b2
    n1 = step_function(z1)
    n2 = step_function(z2)

    z3 = w3[0]*n1 + w3[1]*n2 + b3
    n3 = step_function(z3)

    outputs.append(n3)

# 출력 결과 확인
for i, (inp, out) in enumerate(zip(inputs, outputs)):
    print(f"입력: {inp}, XOR 결과: {results[i]}, 모델 출력: {out}")

import numpy as np
import matplotlib.pyplot as plt

# XOR 연산 입력값과 분류 결과 설정
inputs = [(1, 1), (0, 1), (1, 0), (0, 0)]
results = [0, 1, 1, 0]

# 가중치와 편향 설정
w1= [-2, -2]
w2= [2, 2]
w3=[1,1]
b1= 3
b2=-1
b3=-2

def step_function(x):
    return np.where(x >= 0, 1, 0)

x = np.linspace(-0.5, 1.5, 10)
y = np.linspace(-0.5, 1.5, 10)

X,Y= np.meshgrid(x,y)

z1=w1[0]*X+w1[1]*Y+b1
z2=w2[0]*X+w2[1]*Y+b2
n1=step_function(z1)
n2=step_function(z2)

z3=  w3[0] * n1 + w3[1] * n2+b3
n3=step_function(z3)

# 그래프 그리기
plt.contourf(X, Y, n3, levels=[-np.inf, 0, np.inf],colors=('blue', 'red'), alpha=0.2)
plt.scatter([point[0] for point in inputs], [point[1] for point in inputs], c=results, cmap='bwr')

plt.show()